routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function () {

    /** Formulario de Login */
    Route::get('/', 'AuthController@showLoginForm')->name('login');
    Route::post('login', 'AuthController@login')->name('login.do');
    
    /** Rotas Protegidas */
    Route::group(['middleware' => ['auth']], function () {
        /** Dashboard Home */
        Route::get('home', 'AuthController@home')->name('home');
        Route::get('users/team', 'UserController@team')->name('users.team');
        /**Imoveis */
        Route::post('properties/image-set-cover', 'PropertyController@imageSetCover')->name('properties.imageSetCover');
        Route::delete('properties/image-remove', 'PropertyController@imageRemove')->name('properties.imageRemove');
        Route::resources([
            /** Usuarios */
            'users' => 'UserController',
            /** Empresa */
            'companies' => 'CompanyController',
            /** Imoveis */
            'properties' => 'PropertyController',
        ]);
    });
    
    /** Logout */
    Route::get('logout', 'AuthController@logout')->name('logout');
    
});

resources/views/admin/dashboard.blade.php
@extends('admin.master.master')

@section('content')
<div style="flex-basis: 100%;">
    <section class="dash_content_app">
        <header class="dash_content_app_header">
            <h2 class="icon-tachometer">Dashboard</h2>
        </header>

        <div class="dash_content_app_box">
            <section class="app_dash_home_stats">
                <article class="control radius">
                    <h4 class="icon-users">Clientes</h4>
                    <p><b>Locadores:</b> 100</p>
                    <p><b>Locatários:</b> 100</p>
                    <p><b>Time:</b> 3</p>
                </article>

                <article class="blog radius">
                    <h4 class="icon-home">Imóveis</h4>
                    <p><b>Disponíveis:</b> 100</p>
                    <p><b>Locados:</b> 100</p>
                    <p><b>Total:</b> 200</p>
                </article>

                <article class="users radius">
                    <h4 class="icon-file-text">Contratos</h4>
                    <p><b>Oficializados:</b> 455</p>
                </article>
            </section>
        </div>
    </section>

    <section class="dash_content_app" style="margin-top: 40px;">
        <header class="dash_content_app_header">
            <h2 class="icon-tachometer">Últimos Contratos Cadastrados</h2>
        </header>

        <div class="dash_content_app_box">
            <div class="dash_content_app_box_stage">
                <table id="dataTable" class="nowrap hover stripe" width="100" style="width: 100% !important;">
                    <thead>
                    <tr>
                        <th>Locador</th>
                        <th>Locatário</th>
                        <th>Negócio</th>
                        <th>Início</th>
                        <th>Vigência</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td><a href="" class="text-orange">Robson V. Leite</a></td>
                        <td><a href="" class="text-orange">Gustavo Web</a></td>
                        <td>Locação</td>
                        <td><?= date('d/m/Y'); ?></td>
                        <td>12 meses</td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </section>

    <section class="dash_content_app" style="margin-top: 40px;">
        <header class="dash_content_app_header">
            <h2 class="icon-tachometer">Últimos Imóveis Cadastrados</h2>
        </header>

        <div class="dash_content_app_box">
            <div class="dash_content_app_box_stage">
                <div class="realty_list">
                    <div class="realty_list_item mt-1 mb-1">
                        <div class="realty_list_item_actions_stats">
                            <img src="{{ asset('backend/assets/images/realty.jpeg') }}" alt="">
                            <ul>
                                <li>Venda: R$ 1.000,00</li>
                                <li>Aluguel: R$ 1.000,00</li>
                            </ul>
                        </div>

                        <div class="realty_list_item_content">
                            <h4>#1 Casa Residencial - Campeche</h4>

                            <div class="realty_list_item_card">
                                <div class="realty_list_item_card_image">
                                    <span class="icon-realty-location"></span>
                                </div>
                                <div class="realty_list_item_card_content">
                                    <span class="realty_list_item_description_title">Bairro:</span>
                                    <span class="realty_list_item_description_content">Campeche</span>
                                </div>
                            </div>

                            <div class="realty_list_item_card">
                                <div class="realty_list_item_card_image">
                                    <span class="icon-realty-util-area"></span>
                                </div>
                                <div class="realty_list_item_card_content">
                                    <span class="realty_list_item_description_title">Área Útil:</span>
                                    <span class="realty_list_item_description_content">300 m&sup2;</span>
                                </div>
                            </div>

                            <div class="realty_list_item_card">
                                <div class="realty_list_item_card_image">
                                    <span class="icon-realty-bed"></span>
                                </div>
                                <div class="realty_list_item_card_content">
                                    <span class="realty_list_item_description_title">Domitórios:</span>
                                    <span class="realty_list_item_description_content">2 Quartos<br><span>Sendo 1 suítes</span></span>
                                </div>
                            </div>

                            <div class="realty_list_item_card">
                                <div class="realty_list_item_card_image">
                                    <span class="icon-realty-garage"></span>
                                </div>
                                <div class="realty_list_item_card_content">
                                    <span class="realty_list_item_description_title">Garagem:</span>
                                    <span class="realty_list_item_description_content">2 Vagas<br><span>Sendo 1 cobertas</span></span>
                                </div>
                            </div>

                        </div>

                        <div class="realty_list_item_actions">
                            <ul>
                                <li class="icon-eye">1234 Visualizações</li>
                            </ul>
                            <div>
                                <a href="" class="btn btn-blue icon-eye">Visualizar Imóvel</a>
                                <a href="" class="btn btn-green icon-pencil-square-o">Editar Imóvel</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
@endsection

resources/views/admin/index.blade.php
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <link rel="stylesheet" href="{{ url(mix('backend/assets/css/reset.css')) }}" />
    <link rel="stylesheet" href="{{ url(mix('backend/assets/css/boot.css')) }}" />
    <link rel="stylesheet" href="{{ url(mix('backend/assets/css/login.css')) }}" />
    <link rel="icon" type="image/png" href="{{ url(asset('backend/assets/images/favicon.png')) }}" />

    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>UpAdmin - Site Control</title>
</head>

<body>

    <div class="ajax_response"></div>

    <div class="dash_login">
        <div class="dash_login_left">
            <article class="dash_login_left_box">
                <header class="dash_login_box_headline">
                    <div class="dash_login_box_headline_logo icon-imob icon-notext"></div>
                    <h1>Login</h1>
                </header>

                <form name="login" action="{{ route('admin.login.do') }}" method="post" autocomplete="off">
                    {{-- @csrf --}}
                    <label>
                        <span class="field icon-envelope">E-mail:</span>
                        <input type="email" name="email" value="edipoelwes2@gmail.com" placeholder="Informe seu e-mail" required />
                    </label>

                    <label>
                        <span class="field icon-unlock-alt">Senha:</span>
                        <input type="password" name="password_check" placeholder="Informe sua senha" required />
                    </label>

                    <button class="gradient gradient-orange radius icon-sign-in">Entrar</button>
                </form>

                <footer>
                    <p>Desenvolvido por <a href="https://www.upinside.com.br">www.<b>upinside</b>.com.br</a></p>
                    <p>&copy; <?= date("Y"); ?> - Todos os Direitos Reservados</p>
                    <p class="dash_login_left_box_support">
                        <a target="_blank" class="icon-whatsapp transition text-green"
                            href="https://api.whatsapp.com/send?phone=DDI+DDD+TELEFONE&text=Olá, preciso de ajuda com o login.">Precisa
                            de Suporte?</a>
                    </p>
                </footer>
            </article>
        </div>

        <div class="dash_login_right"></div>

    </div>

    <script src="{{ url(mix('backend/assets/js/jquery.js')) }}"></script>
    <script src="{{ url(mix('backend/assets/js/login.js')) }}"></script>

</body>
</html>